databases:
  - name: fixfit_db
    databaseName: fixfit
    user: fixfit_user

services:
  - type: web
    name: fixfit
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn fixfit.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fixfit_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
      - key: PYTHON_VERSION
        value: "3.12.3"
