databases:
  - name: fixfit_db
    databaseName: fixfit
    user: fixfit

services:
  - type: web
    name: fixfit
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn fixfit.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fixfit_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
